# Site settings
title: kmokidd
description: > # this means to ignore newlines until "baseurl:"
  这里是六六屯笔记的地方 ｜ This is the place where Kidd puts her technical notes
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kmokidd.github.io/" # the base hostname & protocol for your site
twitter_username: kmokidd
github_username:  kmokidd

# Build settings
markdown: kramdown
