# Site settings
title: kmokidd
description: > # this means to ignore newlines until "baseurl:"
  六六做记录的地方 ｜ Where Kidd records something related to tech
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kmokidd.github.io/" # the base hostname & protocol for your site
github_username:  kmokidd

# Build settings
markdown: kramdown
